#!/usr/bin/env bash
# Render the personal repo's codex/AGENTS.md from the Claude-side sources, so
# House Style stays the one file you iterate on and Codex follows.
#
#   render-codex-agents.sh REPO
#
# Reads  REPO/claude/output-styles/House Style.md   (body, frontmatter stripped)
#        REPO/claude/CLAUDE.md                       (two rules, the
#                                                    "## Engineering discipline"
#                                                    section, the Shelby block)
# Writes REPO/codex/AGENTS.md  — only if the rendered content differs.
# Prints one line: RENDER_STATE=unchanged | regenerated | failed: <reason>
# Exit 0 for unchanged/regenerated, 3 for failed (nothing written), 2 usage.
set -euo pipefail

[ $# -eq 1 ] || { echo "usage: render-codex-agents.sh REPO" >&2; exit 2; }
repo="${1%/}"
style="$repo/claude/output-styles/House Style.md"
claude_md="$repo/claude/CLAUDE.md"
out="$repo/codex/AGENTS.md"

fail() { echo "RENDER_STATE=failed: $1"; exit 3; }

[ -f "$style" ]     || fail "missing $style"
[ -f "$claude_md" ] || fail "missing $claude_md"

# --- pieces from CLAUDE.md -------------------------------------------------
rule_halluc="$(grep -E '^[0-9]+\. \*\*No hallucination\*\*' "$claude_md" | head -1 || true)"
rule_naming="$(grep -E '^[0-9]+\. \*\*File naming\*\*' "$claude_md" | head -1 || true)"
[ -n "$rule_halluc" ] || fail "no 'No hallucination' rule in $claude_md"
[ -n "$rule_naming" ] || fail "no 'File naming' rule in $claude_md"
rule_halluc="$(printf '%s' "$rule_halluc" | sed -E 's/^[0-9]+\./1./')"
rule_naming="$(printf '%s' "$rule_naming" | sed -E 's/^[0-9]+\./2./')"

grep -q '^## Engineering discipline$' "$claude_md" || fail "no '## Engineering discipline' section in $claude_md"
grep -q '<!-- shelby:bootstrap start -->' "$claude_md" || fail "no shelby:bootstrap start marker in $claude_md"
grep -q '<!-- shelby:bootstrap end -->' "$claude_md"   || fail "no shelby:bootstrap end marker in $claude_md"

# discipline: heading up to (not incl.) shelby start; trim trailing blank lines
discipline="$(awk '
  /^## Engineering discipline$/ { on=1 }
  /<!-- shelby:bootstrap start -->/ { on=0 }
  on { print }
' "$claude_md" | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}')"

shelby="$(awk '
  /<!-- shelby:bootstrap start -->/ { on=1 }
  on { print }
  /<!-- shelby:bootstrap end -->/ { on=0 }
' "$claude_md")"

# --- House Style body (frontmatter stripped) -------------------------------
first="$(head -1 "$style")"
[ "$first" = "---" ] || fail "House Style.md does not start with YAML frontmatter"
# body = after the second '---' line; then drop leading blank lines
body="$(awk 'NR==1{next} !seen && /^---$/ {seen=1; next} seen {print}' "$style" | sed '/./,$!d')"
[ -n "$body" ] || fail "House Style.md frontmatter never closes (no second ---)"

# --- compose ---------------------------------------------------------------
rendered="$(printf '%s\n\n%s\n\n%s\n%s\n\n%s\n\n%s\n\n%s\n' \
  '<!-- GENERATED by machine:sync (render-codex-agents.sh) from claude/output-styles/House Style.md and claude/CLAUDE.md — edit those; this file is overwritten on every sync. -->' \
  '# Rules' \
  "$rule_halluc" \
  "$rule_naming" \
  "$discipline" \
  "$body" \
  "$shelby")"

if [ -f "$out" ] && [ "$(cat "$out")" = "$rendered" ]; then
  echo "RENDER_STATE=unchanged"
  exit 0
fi
mkdir -p "$(dirname "$out")"
printf '%s\n' "$rendered" > "$out"
echo "RENDER_STATE=regenerated"
