#!/usr/bin/env bash
# Build the developer's global instructions from the Harness profile, so Claude
# and Codex read the same text and the profile stays the one place it is edited.
#
#   render-global-instructions.sh [--adopt] REPO [PROFILE_DIR]
#
# Reads  PROFILE_DIR/Global Instructions.md and PROFILE_DIR/House Style.md
#        (default: the profile bundled with Harness; the argument is a testing seam)
# Writes REPO/claude/CLAUDE.md  — the block between the harness:profile markers is
#                                 replaced; text outside it is the developer's own
#                                 and is never touched
#        REPO/codex/AGENTS.md   — a byte-identical copy
# A CLAUDE.md without the markers is hand-written. Without --adopt nothing is
# written; with --adopt it is replaced by the block, keeping only its Shelby block.
# Prints one line: RENDER_STATE=unchanged | regenerated | adopt-required | failed: <reason>
# Exit 0 for unchanged/regenerated, 4 for adopt-required, 3 for failed, 2 usage.
set -euo pipefail

adopt=0
if [ "${1:-}" = "--adopt" ]; then adopt=1; shift; fi
[ $# -ge 1 ] && [ $# -le 2 ] || { echo "usage: render-global-instructions.sh [--adopt] REPO [PROFILE_DIR]" >&2; exit 2; }
repo="${1%/}"
harness="$(cd "$(dirname "$0")/.." && pwd)"
profile="${2:-$harness/profile}"
rules="$profile/Global Instructions.md"
style="$profile/House Style.md"
target="$repo/claude/CLAUDE.md"
copy="$repo/codex/AGENTS.md"
start='<!-- harness:profile:start -->'
end='<!-- harness:profile:end -->'

fail() { echo "RENDER_STATE=failed: $1"; exit 3; }

[ -s "$rules" ] || fail "missing $rules"
[ -s "$style" ] || fail "missing $style"

# --- the developer's own text: everything outside the managed block ---------
own=""
if [ -s "$target" ]; then
  if grep -qF -- "$start" "$target" && grep -qF -- "$end" "$target"; then
    own="$(awk -v s="$start" -v e="$end" '
      index($0, s) { skip=1 }
      !skip { print }
      index($0, e) { skip=0 }
    ' "$target" | sed '/./,$!d')"
  elif [ "$adopt" -eq 1 ]; then
    own="$(awk '
      /<!-- shelby:bootstrap start -->/ { on=1 }
      on { print }
      /<!-- shelby:bootstrap end -->/ { on=0 }
    ' "$target")"
  else
    echo "RENDER_STATE=adopt-required"
    exit 4
  fi
fi

# --- compose ---------------------------------------------------------------
rendered="$(printf '%s\n%s\n\n%s\n\n%s\n%s\n' \
  "$start" \
  '_Generated by harness:sync from the Harness profile (plugins/harness/profile in Studio-Moser/skills-n-stuff). Edit it there; text outside this block is yours and is kept._' \
  "$(cat "$rules")" \
  "$(cat "$style")" \
  "$end")"
[ -z "$own" ] || rendered="$(printf '%s\n\n%s\n' "$rendered" "$own")"

state=unchanged
for out in "$target" "$copy"; do
  if [ -f "$out" ] && [ "$(cat "$out")" = "$rendered" ]; then continue; fi
  mkdir -p "$(dirname "$out")"
  printf '%s\n' "$rendered" > "$out"
  state=regenerated
done
echo "RENDER_STATE=$state"
