#!/usr/bin/env bats

setup() {
  SCRIPT="${BATS_TEST_DIRNAME}/../scripts/render-codex-agents.sh"
  REPO="${BATS_TEST_TMPDIR}/agents"
  mkdir -p "$REPO/claude/output-styles"
  cat > "$REPO/claude/output-styles/House Style.md" << 'EOF'
---
name: House Style
description: test style
keep-coding-instructions: true
---

# Clear, Concise, Actionable Communication

## Purpose

Say less.
EOF
  cat > "$REPO/claude/CLAUDE.md" << 'EOF'
# Rules

1. **No hallucination** — If you don't know, say so.
2. **Skill precedence** — claude-only rule.
3. **One reviewer per change** — claude-only rule.
4. **Delegate explicitly** — claude-only rule.
5. **File naming** — Title Case with spaces.

## Engineering discipline

Applies to every agent. Stop at the first rung that holds:

1. Does this need to exist at all?

- Bug fix = root cause.

<!-- shelby:bootstrap start -->
## Shelby memory
Use Shelby.
<!-- shelby:bootstrap end -->
EOF
}

@test "renders header, two renumbered rules, discipline, style body, shelby block — in that order" {
  run "$SCRIPT" "$REPO"
  [ "$status" -eq 0 ]
  [ "$output" = "RENDER_STATE=regenerated" ]
  out="$REPO/codex/AGENTS.md"
  [ -f "$out" ]
  head -1 "$out" | grep -q '^<!-- GENERATED by machine:sync (render-codex-agents.sh)'
  grep -qE '^1\. \*\*No hallucination\*\*' "$out"
  grep -qE '^2\. \*\*File naming\*\*' "$out"
  [ "$(grep -c 'Skill precedence' "$out")" -eq 0 ]
  [ "$(grep -c 'Delegate explicitly' "$out")" -eq 0 ]
  grep -q '^## Engineering discipline$' "$out"
  grep -q '^# Clear, Concise, Actionable Communication$' "$out"
  [ "$(grep -c '^keep-coding-instructions' "$out")" -eq 0 ]
  [ "$(grep -c '^name: House Style' "$out")" -eq 0 ]
  grep -q '<!-- shelby:bootstrap start -->' "$out"
  grep -q '<!-- shelby:bootstrap end -->' "$out"
  # order: rules < discipline < style < shelby
  r=$(grep -n '^# Rules$' "$out" | cut -d: -f1)
  d=$(grep -n '^## Engineering discipline$' "$out" | cut -d: -f1)
  s=$(grep -n '^# Clear, Concise' "$out" | cut -d: -f1)
  m=$(grep -n 'shelby:bootstrap start' "$out" | cut -d: -f1)
  [ "$r" -lt "$d" ] && [ "$d" -lt "$s" ] && [ "$s" -lt "$m" ]
}

@test "second run with no source change reports unchanged and leaves the file byte-identical" {
  "$SCRIPT" "$REPO" > /dev/null
  cp "$REPO/codex/AGENTS.md" "${BATS_TEST_TMPDIR}/first.md"
  run "$SCRIPT" "$REPO"
  [ "$status" -eq 0 ]
  [ "$output" = "RENDER_STATE=unchanged" ]
  cmp -s "$REPO/codex/AGENTS.md" "${BATS_TEST_TMPDIR}/first.md"
}

@test "a source edit regenerates" {
  "$SCRIPT" "$REPO" > /dev/null
  printf '\nSay even less.\n' >> "$REPO/claude/output-styles/House Style.md"
  run "$SCRIPT" "$REPO"
  [ "$output" = "RENDER_STATE=regenerated" ]
  grep -q 'Say even less.' "$REPO/codex/AGENTS.md"
}

@test "missing discipline heading fails with exit 3 and writes nothing" {
  sed -i.bak '/^## Engineering discipline$/d' "$REPO/claude/CLAUDE.md"
  run "$SCRIPT" "$REPO"
  [ "$status" -eq 3 ]
  [[ "$output" == RENDER_STATE=failed:* ]] || return 1
  [ ! -e "$REPO/codex/AGENTS.md" ]
}

@test "missing House Style file fails with exit 3" {
  rm "$REPO/claude/output-styles/House Style.md"
  run "$SCRIPT" "$REPO"
  [ "$status" -eq 3 ]
  [[ "$output" == *"House Style"* ]]
}

@test "usage error exits 2" {
  run "$SCRIPT"
  [ "$status" -eq 2 ]
}
